FROM node:16.20-bullseye

# Install build essential for compiling mediasoup
RUN \
	set -x \
	&& apt-get update \
	&& apt-get install -y net-tools build-essential python3 python3-pip valgrind ffmpeg

RUN mkdir -p /service
WORKDIR /service

COPY package*.json .
RUN npm install
COPY . .

EXPOSE 3000
CMD npm run db:migrate && npm run seed && npm run start:dev
